/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p urfkillwlan.h -c UrfkillWlan urfkillwlan.xml org.freedesktop.URfkill.Killswitch
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef URFKILLWLAN_H_1416319828
#define URFKILLWLAN_H_1416319828

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.freedesktop.URfkill.Killswitch
 */
class UrfkillSwitch: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.URfkill.Killswitch"; }

public:
    UrfkillSwitch(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~UrfkillSwitch();

    Q_PROPERTY(int state READ state)
    inline int state() const
    { return qvariant_cast< int >(property("state")); }

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void StateChanged();
};

#endif
