/* secret-agent.h generated by valac 0.14.0, the Vala compiler, do not modify */


#ifndef __SECRET_AGENT_H__
#define __SECRET_AGENT_H__

#include <glib.h>
#include <glib-object.h>
#include <nm-secret-agent.h>

G_BEGIN_DECLS


#define UNITY_SETTINGS_TYPE_SECRET_AGENT (unity_settings_secret_agent_get_type ())
#define UNITY_SETTINGS_SECRET_AGENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_SETTINGS_TYPE_SECRET_AGENT, UnitySettingsSecretAgent))
#define UNITY_SETTINGS_SECRET_AGENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_SETTINGS_TYPE_SECRET_AGENT, UnitySettingsSecretAgentClass))
#define UNITY_SETTINGS_IS_SECRET_AGENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_SETTINGS_TYPE_SECRET_AGENT))
#define UNITY_SETTINGS_IS_SECRET_AGENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_SETTINGS_TYPE_SECRET_AGENT))
#define UNITY_SETTINGS_SECRET_AGENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_SETTINGS_TYPE_SECRET_AGENT, UnitySettingsSecretAgentClass))

typedef struct _UnitySettingsSecretAgent UnitySettingsSecretAgent;
typedef struct _UnitySettingsSecretAgentClass UnitySettingsSecretAgentClass;
typedef struct _UnitySettingsSecretAgentPrivate UnitySettingsSecretAgentPrivate;

struct _UnitySettingsSecretAgent {
	NMSecretAgent parent_instance;
	UnitySettingsSecretAgentPrivate * priv;
};

struct _UnitySettingsSecretAgentClass {
	NMSecretAgentClass parent_class;
};


GType                     unity_settings_secret_agent_get_type  (void) G_GNUC_CONST;
UnitySettingsSecretAgent* unity_settings_secret_agent_new       (void);
UnitySettingsSecretAgent* unity_settings_secret_agent_construct (GType object_type);


G_END_DECLS

#endif
